# ===================================================================
# This Docker Compose file is configured for a development environment
# -------------------------------------------------------------------
services:
  db:
    image: postgres:13
    volumes:
      - wildflower_designs_pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: c44cae69846fab92331f533e6fe1d8bd

  web:
    build: .
    command:
      - sh
      - -c
      - |
        rm -f tmp/pids/server.pid && \
        bundle exec rails db:create db:migrate && \
        bundle exec rails assets:precompile && \
        bundle exec rails s -p 8538 -b '0.0.0.0'
    volumes:
      - /share/Public/docker/wildflower_designs:/var/www/wildflower_designs
    ports:
      - "8538:8538"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: c44cae69846fab92331f533e6fe1d8bd
      RAILS_ENV: development
      RACK_ENV: development
      RAILS_MASTER_KEY: c44cae69846fab92331f533e6fe1d8bd
      DATABASE_URL: "postgresql://postgres:c44cae69846fab92331f533e6fe1d8bd@db:5432/wildflower_designs_development"
      GAME_API_PORT: "https://jeremyd.net"

volumes:
  wildflower_designs_pg_data: