default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "wildflower_designs_development") %>
  username: <%= ENV.fetch("DB_USERNAME", "your_default_username") %>
  password: <%= ENV.fetch("DB_PASSWORD", "your_default_password") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "wildflower_designs_test") %>
  username: <%= ENV.fetch("DB_USERNAME", "your_default_username") %>
  password: <%= ENV.fetch("DB_PASSWORD", "your_default_password") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") %>
